-- Migration to create UserDrawing and UserLevel tables
-- (these were applied directly on the DB in a previous session)
-- NOTE: UserLevel and UserDrawing are now created by proper migrations
-- 20260722000000_add_user_levels and 20260722000001_add_user_drawings.
-- This migration is kept as a no-op for existing deployments.